### ISSUE TITLE
Multiple Transformers per Column

### ISSUE THREAD

**Issue by MNic** [fny/thecurator#3]
I'd be interested in your thoughts on adding multi-transform handling whenever you get a minute.  I think we discussed this before and we either just didn't do it, or there was an underlying desire to keep the process as simple as possible that overrode the functionality creep.

It would certainly simplify the re-use / idempotency of some of our transformers, but if it's not something you want to add, I think we can work with it.

I've already made the changes and tested with existing tests, but need to add a few new ones.  Happy to submit a PR whenever the tests are done.

## Example

Descriptions will take a list of transforms or a single.

```yaml
  - name: name
    description: >
      Lab name
    type: string
    transform: 
      - transformers.common.uppercase
      - transformers.lab.name
```

Transformer application is moved to a loop over the transforms if the transform is a list

```python
####
                elif isinstance(transform, list):
                    for tr in transform:
                        if hasattr(tr, 'requires_row'):
                            raw_row[column_name] = tr(raw_row)
                        else:
                            if raw_row.get(column_name):
                                raw_row[column_name] = tr(raw_row.get(column_name)
####
```
