### ISSUE TITLE
Write a column transform to a new column

### ISSUE THREAD

**Issue by MNic** [fny/thecurator#5]
Current functionality is one transform per column that outputs, essentially in place.

`BLOOD PRESSURE` -> `transform.lower()` -> `blood pressure`

This is great until we need to output multiple different versions of a transformed input.

`BLOOD PRESSURE` -> `transform.under()` -> `BLOOD_PRESSURE`
`BLOOD PRESSURE` -> `transform.lower()` -> `blood pressure`

We currently handle this by querying the column twice, with different names and apply each transform individually. This is fine, and functional, but requires some careful query redundancy and moving unnecessary data, sometimes a lot of it.

Implementation would likely require a new addition to the `description.yml` specifying a destination column or columns for each incoming column.  Along with the other issues i've been spamming you with, this could be quite complicated.  

```yaml

  - name: name
    description: >
      Lab name
    type: string
    transform: 
      - transformers.common.uppercase
      - transformers.lab.name
    destination_name:
      - name_uppercase
      - name
```

or 

```yaml

  - name: name
    description: >
      Lab name
    type: string
    transforms: 
      - destination_name: name_uppercase
        transform: transformers.common.uppercase
      - destination_name: name
        transform: transformers.lab.name
```

Happy to discuss and attempt to implement if it's something you're willing to add.
